// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xCDC3 },
    { 3, 0xD68E },
    { 3, 0xDC65 },
    { 3, 0xE237 },
    { 3, 0xE806 },
    { 3, 0xEDD3 },
    { 3, 0xF353 },
    { 3, 0xF843 },
    { 3, 0xFBE9 },
    { 4, 0xC000 },
    { 4, 0xC391 },
    { 4, 0xC6F8 },
    { 4, 0xCA05 },
    { 4, 0xCC49 },
    { 3, 0xFF80 },
    { 3, 0xFF93 },
    { 3, 0xFF9F },
    { 3, 0xFFAA },
    { 3, 0xFFB3 }
};

#define SCR_ENDING_2_BIN                0
#define SCR_COMINGSOON_BIN              1
#define TILESET_BASEMENT_BIN            2
#define TILESET_HITECH_BIN              3
#define TILESET_MINE_BIN                4
#define TILESET_FOREST_BIN              5
#define TILESET_SCHOOL_BIN              6
#define SCR_MT_MARCO_BIN                7
#define MAP_FOREST1_BIN                 8
#define MAP_BASEMENT1_BIN               9
#define SCR_MENU_DEMO_BIN               10
#define MAP_HITECH1_BIN                 11
#define MAP_SCHOOL2_BIN                 12
#define MAP_MINE3_BIN                   13
#define SCR_GAME_OVER_BIN               14
#define HITECH_BEHS_BIN                 15
#define BASEMENT_BEHS_BIN               16
#define MINE_BEHS_BIN                   17
#define FOREST_BEHS_BIN                 18
#define SCHOOL_BEHS_BIN                 19

