// librarian.h
// Generated by The Librarian
// Copyleft 2012 The Mojon Twins
 
typedef struct {
   unsigned char ramPage;
   unsigned int ramOffset;
} RESOURCE;
 
RESOURCE resources [] = {
   {3, 49152},   // 0: title.bin
   {3, 50584},   // 1: marco.bin
   {3, 51757},   // 2: ending.bin
   {3, 52097},   // 3: talkg.bin
   {3, 52576},   // 4: talkc.bin
   {3, 53129},   // 5: arcon.bin
   {3, 53997},   // 6: tardismenu.bin
   {3, 57546},   // 7: itemsts.bin
   {3, 57991},   // 8: level0c.bin
   {3, 59853},   // 9: level0r1.bin
   {3, 60317},   // 10: level0r2.bin
   {3, 60667},   // 11: level2c.bin
   {3, 62340},   // 12: level2r1.bin
   {3, 62786},   // 13: level2r2.bin
   {3, 63136},   // 14: level5c.bin
   {3, 65069},   // 15: level5r1.bin
   {4, 49152},   // 16: level6c.bin
   {4, 50955},   // 17: level6r1.bin
   {4, 51434},   // 18: levelTc.bin
   {4, 53003},   // 19: levelTr1.bin
   {4, 53411},   // 20: levelTr2.bin
   {4, 53774}    // 21: levelTr3.bin
};
 
void get_resource (unsigned char res, unsigned int dest) {
    unpack_RAMn (resources [res].ramPage, resources [res].ramOffset, dest);
}
 
#ifdef NEED_RAMN_OFFSETS
int read_offset (unsigned char res, unsigned int offs) {
	ram_page [0] = resources [res].ramPage;
    ram_address [0] = (resources [res].ramOffset + offs);
    #asm
        di
        ld a, (_ram_page)
        ld b, a
        call SetRAMBank
        ld hl, (_ram_address)
        ld de, _asm_int
        ldi
        ldi
        ld b, 0
        call SetRAMBank
        ei
    #endasm
    return asm_int [0];
}
#endif

// Defines
#define TITLE_BIN           	0
#define MARCO_BIN           	1
#define ENDING_BIN          	2
#define TALKG_BIN           	3
#define TALKC_BIN           	4
#define ARCON_BIN           	5
#define TARDISMENU_BIN      	6
#define ITEMSTS_BIN         	7
#define LEVEL0C_BIN         	8
#define LEVEL0R1_BIN        	9
#define LEVEL0R2_BIN        	10
#define LEVEL2C_BIN         	11
#define LEVEL2R1_BIN        	12
#define LEVEL2R2_BIN        	13
#define LEVEL5C_BIN         	14
#define LEVEL5R1_BIN        	15
#define LEVEL6C_BIN         	16
#define LEVEL6R1_BIN        	17
#define LEVELTC_BIN         	18
#define LEVELTR1_BIN        	19
#define LEVELTR2_BIN        	20
#define LEVELTR3_BIN        	21
