// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xCDC3 },
    { 3, 0xDA1A },
    { 3, 0xE2F7 },
    { 3, 0xEA00 },
    { 3, 0xF010 },
    { 3, 0xF5E7 },
    { 4, 0xC000 },
    { 4, 0xC5D2 },
    { 4, 0xCBA1 },
    { 4, 0xD16E },
    { 4, 0xD733 },
    { 4, 0xDCB3 },
    { 4, 0xE198 },
    { 4, 0xE652 },
    { 4, 0xEB05 },
    { 3, 0xFBBE },
    { 4, 0xEF91 },
    { 4, 0xF371 },
    { 4, 0xF74F },
    { 4, 0xFAF4 },
    { 6, 0xC000 },
    { 6, 0xC389 },
    { 6, 0xC711 },
    { 6, 0xCA94 },
    { 6, 0xCE07 },
    { 6, 0xD16E },
    { 6, 0xD4AA },
    { 6, 0xD7D3 },
    { 6, 0xDAEA },
    { 6, 0xDDF7 },
    { 6, 0xE0E7 },
    { 6, 0xE3A1 },
    { 6, 0xE658 },
    { 6, 0xE8F8 },
    { 6, 0xEB7E },
    { 6, 0xEDCF },
    { 6, 0xF01E },
    { 6, 0xF262 },
    { 6, 0xF476 },
    { 6, 0xF61D },
    { 6, 0xF7AC },
    { 4, 0xFE8B },
    { 6, 0xF928 },
    { 6, 0xFA3E },
    { 6, 0xFB4A },
    { 6, 0xFC3E },
    { 6, 0xFD31 },
    { 6, 0xFE04 },
    { 6, 0xFE9C },
    { 3, 0xFFAC },
    { 3, 0xFFC8 },
    { 3, 0xFFDB },
    { 4, 0xFFF4 },
    { 3, 0xFFE7 },
    { 3, 0xFFF0 },
    { 6, 0xFEF2 },
    { 6, 0xFEFB }
};

#define SCR_ENDING_2_BIN                0
#define SCR_ENDING_1_BITMAP_BIN         1
#define SCR_CREDITS_BIN                 2
#define SCR_INTRO_MINE_BIN              3
#define SCR_INTRO_HITECH_BIN            4
#define TILESET_BASEMENT_BIN            5
#define TILESET_SECRET_BIN              6
#define TILESET_HITECH_BIN              7
#define TILESET_MINE_BIN                8
#define TILESET_FOREST_BIN              9
#define SCR_INTRO_FOREST_BIN            10
#define TILESET_SCHOOL_BIN              11
#define TILESET_TRAINING_BIN            12
#define SCR_INTRO_BASEMENT_BIN          13
#define SCR_UBHRES_BIN                  14
#define SCR_MT_MARCO_BIN                15
#define MAP_FOREST3_BIN                 16
#define MAP_BASEMENT4_BIN               17
#define MAP_FOREST2_BIN                 18
#define MAP_FOREST1_BIN                 19
#define MAP_BASEMENT1_BIN               20
#define SCR_INTRO_SCHOOL_BIN            21
#define MAP_BASEMENT2_BIN               22
#define MAP_HITECH2_BIN                 23
#define MAP_SECRET_BIN                  24
#define MAP_HITECH1_BIN                 25
#define SCR_MENU_BIN                    26
#define MAP_FOREST4_BIN                 27
#define MAP_BASEMENT3_BIN               28
#define MAP_SCHOOL2_BIN                 29
#define MAP_SCHOOL1_BIN                 30
#define MAP_MINE2_BIN                   31
#define MAP_MINE1_BIN                   32
#define MAP_SCHOOL4_BIN                 33
#define MAP_HITECH3_BIN                 34
#define MAP_SCHOOL3_BIN                 35
#define MAP_MINE4_BIN                   36
#define MAP_MINE3_BIN                   37
#define MAP_HITECH4_BIN                 38
#define MAP_LUCA1_BIN                   39
#define MAP_LUCA3_BIN                   40
#define MAP_LUCA4_BIN                   41
#define SCR_MTLOGO_BIN                  42
#define MAP_TRAINING_BIN                43
#define SCR_ENDING_1_ATTRS_4_BIN        44
#define SCR_GAME_OVER_BIN               45
#define MAP_LUCA2_BIN                   46
#define SCR_ENDING_1_ATTRS_3_BIN        47
#define SCR_ENDING_1_ATTRS_2_BIN        48
#define SCR_ENDING_1_ATTRS_1_BIN        49
#define SCR_ENDING_1_ATTRS_0_BIN        50
#define HITECH_BEHS_BIN                 51
#define BASEMENT_BEHS_BIN               52
#define MINE_BEHS_BIN                   53
#define TRAINING_BEHS_BIN               54
#define SCHOOL_BEHS_BIN                 55
#define FOREST_BEHS_BIN                 56
#define SECRET_BEHS_BIN                 57

