// MTE MK1 (la Churrera) v5.0
// Copyleft 2010-2014, 2020 by the Mojon Twins

// Generated by The Librarian v2.1 20200823
// Copyleft 2020 by The Mojon Twins

typedef struct {
    unsigned char ramPage;
    unsigned int ramOffset;
} RESOURCE;

RESOURCE resources [] = {
    { 3, 0xC000 },
    { 3, 0xCDC3 },
    { 3, 0xDA1A },
    { 3, 0xE2F7 },
    { 3, 0xEA00 },
    { 3, 0xF010 },
    { 3, 0xF60A },
    { 4, 0xC000 },
    { 4, 0xC5C5 },
    { 4, 0xCB7D },
    { 4, 0xD122 },
    { 4, 0xD6A5 },
    { 4, 0xDC11 },
    { 4, 0xE179 },
    { 4, 0xE633 },
    { 4, 0xEAE6 },
    { 3, 0xFBD7 },
    { 4, 0xEF4C },
    { 4, 0xF2E1 },
    { 4, 0xF66A },
    { 4, 0xF9EE },
    { 6, 0xC000 },
    { 6, 0xC369 },
    { 6, 0xC6C0 },
    { 6, 0xCA02 },
    { 6, 0xCD3E },
    { 6, 0xD056 },
    { 6, 0xD36C },
    { 6, 0xD67D },
    { 6, 0xD98C },
    { 6, 0xDC95 },
    { 6, 0xDF7E },
    { 6, 0xE257 },
    { 4, 0xFD61 },
    { 6, 0xE51D },
    { 6, 0xE7A3 },
    { 6, 0xEA13 },
    { 6, 0xEC81 },
    { 6, 0xEEBD },
    { 6, 0xF0D1 },
    { 6, 0xF23A },
    { 6, 0xF350 },
    { 6, 0xF45C },
    { 6, 0xF550 },
    { 6, 0xF623 },
    { 3, 0xFFA1 },
    { 6, 0xF6BB }
};

#define SCR_ENDING_2_BIN                0
#define SCR_ENDING_1_BITMAP_BIN         1
#define SCR_CREDITS_BIN                 2
#define SCR_INTRO_MINE_BIN              3
#define SCR_INTRO_HITECH_BIN            4
#define SCR_MT_MARCO_BIN                5
#define TILESET_HITECH_BIN              6
#define SCR_INTRO_FOREST_BIN            7
#define TILESET_FOREST_BIN              8
#define TILESET_MINE_BIN                9
#define TILESET_SECRET_BIN              10
#define TILESET_BASEMENT_BIN            11
#define TILESET_SCHOOL_BIN              12
#define SCR_INTRO_BASEMENT_BIN          13
#define SCR_UBHRES_BIN                  14
#define TILESET_TRAINING_BIN            15
#define MAP_FOREST3_BIN                 16
#define MAP_BASEMENT4_BIN               17
#define SCR_INTRO_SCHOOL_BIN            18
#define MAP_FOREST2_BIN                 19
#define MAP_SECRET_BIN                  20
#define MAP_HITECH2_BIN                 21
#define MAP_FOREST1_BIN                 22
#define MAP_BASEMENT1_BIN               23
#define SCR_MENU_BIN                    24
#define MAP_FOREST4_BIN                 25
#define MAP_MINE1_BIN                   26
#define MAP_BASEMENT2_BIN               27
#define MAP_MINE2_BIN                   28
#define MAP_HITECH1_BIN                 29
#define MAP_SCHOOL2_BIN                 30
#define MAP_SCHOOL1_BIN                 31
#define MAP_BASEMENT3_BIN               32
#define MAP_SCHOOL4_BIN                 33
#define MAP_HITECH3_BIN                 34
#define MAP_MINE4_BIN                   35
#define MAP_MINE3_BIN                   36
#define MAP_SCHOOL3_BIN                 37
#define MAP_HITECH4_BIN                 38
#define SCR_MTLOGO_BIN                  39
#define MAP_TRAINING_BIN                40
#define SCR_ENDING_1_ATTRS_4_BIN        41
#define SCR_GAME_OVER_BIN               42
#define SCR_ENDING_1_ATTRS_3_BIN        43
#define SCR_ENDING_1_ATTRS_2_BIN        44
#define SCR_ENDING_1_ATTRS_1_BIN        45
#define SCR_ENDING_1_ATTRS_0_BIN        46

